language: ruby
cache: bundler
bundler_args: --without benchmarks tools
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
  - bundle exec rake
rvm:
  - 2.6.3
  - 2.5.5
  - 2.4.6
  - jruby-9.2.7.0
env:
  global:
    - COVERAGE=true
  matrix:
    - USE_SCHEMA_MASTER=true
    - USE_TYPES_MASTER=true
    - USE_SCHEMA_MASTER=false
    - USE_TYPES_MASTER=false
matrix:
  allow_failures:
    - rvm: jruby-9.2.7.0
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
      - https://dry-rb.zulipchat.com/api/v1/external/travis?api_key=SY8LLz6fShd4TJeLDXEdT0eBEgRqT2lv&stream=notifications&topic=ci
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
