language: ruby
cache: bundler
sudo: false
bundler_args: --without benchmarks tools
before_install: gem update --system
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - "[ -d coverage ] && ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
script:
  - bundle exec rake
rvm:
  - 2.6.0
  - 2.5.3
  - 2.4.5
  - 2.3.8
  - jruby-9.2.5.0
env:
  global:
    - COVERAGE=true
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/19098b4253a72c9796db
    on_success: change # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: false # default: false
