name: sync_configs

on:
  repository_dispatch:

jobs:
  sync-configs:
    runs-on: ubuntu-latest
    steps:
      - name: "Debug"
        run: echo "${{toJson(github.event)}}"
      - uses: actions/checkout@v1
      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: "2.6.x"
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3 --without benchmarks sql
      - name: Symlink ossy
        run: ln -sf "$(bundle show ossy)/bin/ossy" bin/ossy
      - name: Update configuration files from devtools
        if: github.event.action == 'sync_configs'
        env:
          GITHUB_LOGIN: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        run: bin/ossy github update_file dry-rb/devtools .github/workflows/docsite.yml
